"""fix models

Revision ID: 14ca49ef95a0
Revises: 932b500f9c4a
Create Date: 2025-09-06 16:12:35.673394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14ca49ef95a0'
down_revision: Union[str, Sequence[str], None] = '932b500f9c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health_profiles', 'height_cm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('health_profiles', 'weight_kg',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_health_profiles_id'), 'health_profiles', ['id'], unique=False)
    op.alter_column('meal_plans', 'plan',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.alter_column('meal_plans', 'plan',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_health_profiles_id'), table_name='health_profiles')
    op.alter_column('health_profiles', 'weight_kg',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('health_profiles', 'height_cm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
